project:
  type: website
  resources: 
    - "data/ICECBPdata.csv"
    - "sources/"
website:
  title: "ice.dashboard"
  navbar:
    left:
      - href: index.qmd
        text: About
      - href: Variables.qmd
        text: Variables
      - href: inclusioncriteria.qmd
        text: Inclusion Criteria
      - href: database.qmd
        text: Database
      - href: sources.qmd
        text: Sources
      - href: cards2.qmd
        text: Individual Data Cards
      - href: faq.qmd
        text: FAQ
  
  page-footer:
    left: "Copyright 2026, Rachel Gorman"
    center: "Built with [Quarto](https://quarto.org/) • Coded in [R](https://r-project.org) • Hosted on [Github](https://github.com)"

format:
  html:
    theme: lumen
    css: styles.css
    toc: false
    smooth-scroll: true
    embed-resources: true