---
title: "Cards"
---

```{r}
#| include: false
library(tidyverse)
library(glue)
library(htmltools)

deaths <- read_csv("data/ICECBPdata.csv")
```

```{r, echo=FALSE, results='asis'}

for(i in seq_len(nrow(deaths))){

cat(
glue::glue('

::: {{.card .mb-3}}

::: {{.card-header}}

{deaths$Name[i]}

:::

::: {{.card-body}}

**Date of Death:** {deaths$Date[i]}

<br>

**Location:** {deaths$City[i]}, {deaths$State[i]}

<br>

**Cause of Death (Official):** {deaths$`Cause of Death (Official)`[i]}

:::

:::

')
)

}

```
```{r, echo=FALSE, results='asis'}
#| output: asis

library(glue)
library(htmltools)

# Replace NA values so cards do not display NA
deaths <- deaths %>%
  mutate(
    across(
      everything(),
      ~ifelse(is.na(.), "-", .)
    )
  )


for(i in seq_len(nrow(deaths))){

cat(glue::glue('

::: {{.card .shadow-sm .mb-4}}

::: {{.card-header}}

## {deaths$Name[i]}

**{deaths$Date[i]}**

:::


::: {{.card-body}}

<div class="mb-3">

<span class="badge bg-secondary">
Age: {deaths$Age[i]}
</span>

<span class="badge bg-secondary">
Gender: {deaths$Gender[i]}
</span>

</div>


<p>
<strong>Location:</strong>
{deaths$Country[i]}, {deaths$State[i]}, {deaths$City[i]}
</p>


<div class="mb-3">

<span class="badge bg-primary">
{deaths$Custody[i]}
</span>

<span class="badge bg-danger">
Cause of Death: {deaths$`Cause of Death (Official)`[i]}
</span>

</div>


<button 
class="btn btn-outline-primary btn-sm"
type="button"
data-bs-toggle="collapse"
data-bs-target="#record{i}">

View Full Record

</button>


<div class="collapse mt-4" id="record{i}">

<hr>


<h5>Location of Death</h5>

<p>
<strong>Location:</strong><br>
{deaths$Country[i]}, {deaths$State[i]}, {deaths$City[i]}, {deaths$County[i]}
</p>


<p>
<strong>Coordinates:</strong><br>
Latitude: {deaths$Latitude[i]}<br>
Longitude: {deaths$Longitude[i]}
</p>



<h5>Cause of Death</h5>

<p>
<strong>Official:</strong><br>
{deaths$`Cause of Death (Official)`[i]}
</p>

<p>
<strong>Unofficial:</strong><br>
{deaths$`Cause of Death (Unofficial)`[i]}
</p>



<h5>Facilities & Transfers</h5>

<p>
{deaths$`Facilities & Transfers`[i]}
</p>



<h5>Other Notes</h5>

<p>
{deaths$`Other Notes`[i]}
</p>



<h5>Sources</h5>

<p>
<a href="{deaths$`Drive Link to Sources`[i]}" target="_blank">
View Source Documents
</a>
</p>


</div>

:::

:::

'))

}
```