---
title: "Inclusion Criteria"
---

::: {.text-chunk}

## What is this project about? [Move to homepage]

:::


::: {.text-chunk}

## How do I choose which deaths to include vs exclude?

I am looking at deaths that have occurred as a result of interaction with ICE/CBP systems or agents. That includes deaths that have occurred while an individual is in custody in a detention center, a hospital, in transit, in a public jail, at a field office, or any other location. For individuals who have died in ICE/CBP custody they are legally required to produce a news release as well as a “Detainee Death Report” which should give more information on how the individual died. For the news release: “In 2021, ICE issued a policy — Notification, Review, and Reporting Requirements for Detainee Deaths — that governs the initial notification, review and ongoing reporting about the death of an individual in ICE custody. In accordance with the policy, ICE notifies the relevant parties and reports the death of any detained alien in a timely, accurate and appropriate manner. ICE notifies the next of kin, appropriate consulate, relevant DHS and ICE stakeholders, U.S. Congress and the public about each detained alien death. [ice.gov detainee death reporting](https://www.ice.gov/detain/detainee-death-reporting)”. For the death reports: “Congressional requirements in the DHS Appropriations Bill (2018) and amended in the DHS Appropriations Bill (2019) obligate ICE to make reports regarding in-custody deaths public within 90 days [reference House Report 116-9, page 480](https://www.congress.gov/116/crpt/hrpt9/CRPT-116hrpt9.pdf)and [ice.gov detainee death reporting](https://www.ice.gov/detain/detainee-death-reporting)". Any individual who has died in ICE/CBP custody and has been reported by ICE/CBP is included in this dataset within the time range of 2026-2018 (currently updating). 

This is a bit harder to track for individuals who are not in ICE/CBP custody and is where it gets harder to define exactly what is included vs excluded. ICE/CBP is not legally obligated to report on when they have killed an individual outside of their custody and I am relying on a combination of sources to identify individuals who have been killed by ICE/CBP while not in their custody. So how do I define that? I use this logic to include or exclude individuals: if this individual had not been in contact with ICE/CBP, would this individual have died the way that they did? I will give a few examples to demonstrate this logic:

1. Nurul Amin Shah Alam was 56 years old and nearly blind. Shah Alam was released from Erie County Holding Center to federal authorities on February 19, 2026 around 4:30 pm. Border Patrol detained him briefly before determining he was not eligible for deportation. Border Patrol then dropped off Shah Alam outside of a closed Tim Hortons after 8 pm without notifying either his family or his attorney. Temperatures dropped below freezing and there was a light snow. His attorney reported him missing on February 22nd, a detective opened an investigation on February 23rd before closing it that afternoon and soon after reopening it. On February 24th, a woman placed a 911 call reporting that she had seen an unmoving man on Perry Street, a six and a half mile drive away from the Tim Horton's, and that man was identified as Shah Alam and pronounced deceased at the scene. On April 1, the Erie County Medical Examiner reported that they had determined that the cause of death was due to complications from an ulcer that resulted from hypothermia and dehydration and that the manner of death was homicide. Shah Alam’s death was a clear and direct result of his interaction with ICE/CBP agents and he would have never died in that manner if he had not been released to ICE, even temporarily. ICE acted in a way that was criminally negligent and harmful. [link to source documents](https://gormanr33.github.io/ice.dashboard/sources/2026.02.24%20-%20Nurul%20Amin%20Shah%20Alam/) 

2. Renee Nicole Good was 37 years old. She was parked in her SUV on a one-way street when an ICE agent, Jonathan Ross, began to circle her car on foot. Other ICE agents approached her car and began giving her conflicting orders to drive forward or move back. Good briefly reversed her SUV before driving forward and away from the ICE agents when Jonathan Ross fired three shots through her vehicle windshield and windows as Goods' vehicle passed him, turning away from him. Ms. Good would not have been shot if Jonathan Ross was not there, acting in the capacity of an ICE agent. [link to source documents](https://gormanr33.github.io/ice.dashboard/sources/2026.01.07%20-%20Renee%20Nicole%20Good/)

3. Juan Jairo Coronilla Duran, 28, was fleeing from ICE agents during an “enforcement action” and was hit by a tractor trailer. Mr. Coronilla would not have been fatally struck by a tractor trailer if he was not fleeing from ICE agents. [link to source documents](https://gormanr33.github.io/ice.dashboard/sources/2026.07.14%20-%20Juan%20Jairo%20Coronilla%20Duran/)

For these cases, I include incidents where three independent and credible sources have reported on the incident. In a majority of these cases, DHS does not acknowledge the death much less take any kind of fault or responsibility on. If DHS or another highly elected government official acknowledges the death and the culpability of DHS’s role in it, I will include this as a source.

:::


::: {.text-chunk}

## How do I choose my sources?

This dataset is based solely on open source, publicly available information. All data in this dataset is replicable and can be found outside of the dataset. As part of this project, I have been collecting and documenting each source I use for each individual as well as archiving the live web source to the Internet Archive when possible (I do not have the capacity to update and work on this project every day so sometimes I am using sources that have been published days, weeks, months beforehand and have been edited. When I do access the source I will archive it). Each individual incident has at least three sources attached to it. For individuals who are in DHS custody at the time of their death, two of these sources are from DHS themselves. One source is the ICE/CBP news release and the other source is the ICE/CBP “detainee death reports” that are published on official government websites. For individuals who are not in DHS custody at the time of their death, I use at least three verified and reputable news agencies reports on the incident. All individuals have news articles as their sources, and I try to gather a range of news sites that are diverse across political leanings, location of the news organization, and size of the media institution. 

Primary sources include but are not limited to: news articles, news releases, press statements, autopsy reports, detainee death reports, official autopsies, and legal/court documents. Secondary sources include but are not limited to: social media posts (specifically ICE/CBP/DHS official government accounts and posts on X, formerly known as Twitter), YouTube videos, etc.

:::


::: {.text-chunk}

## Why do you include both official and unofficial causes of death?

There are two coded columns in this dataset that are **“Cause of Death (Official)”** and **“Cause of Death (Unofficial)”**. These columns and subsequent coding schemes have stemmed from the following:

1. For individuals who are in DHS custody, there is often not an immediate release of information of how the individual died. DHS is legally obligated to release a death report for all individuals who have died in custody; “Congressional requirements in the DHS Appropriations Bill (2018) and amended in the DHS Appropriations Bill (2019) obligate ICE to make reports regarding in-custody deaths public within 90 days [reference House Report 116-9, page 480](https://www.congress.gov/116/crpt/hrpt9/CRPT-116hrpt9.pdf) and [ice.gov detainee death reporting](https://www.ice.gov/detain/detainee-death-reporting)". Sometimes, DHS will put information in the news releases that they are also legally obligated to release on how an individual died but it can change, is not always accurate to the later released detainee death report, and is sometimes worded in ways that are misleading or later on just incorrect. Outside news agencies have the resources and the inclination to discuss with the individuals families about information they have leading up to the individual's death, including medical history, conversations (or lack of contact) with the individual, and other information that the government does not report on. These sources of information offer insights into how the individual was treated leading up to their death and can give a clearer picture of the medical history and potential medical neglect, as well as how the families were notified of the individual's death and if that notification from DHS differed from their official statements (it often does, if the family is granted the courtesy of a notification and explanation. Most families are left in the dark and have to pursue answers on their own, which is time consuming, infuriating, purposefully confusing and can be costly.). 

2. Individuals who are in DHS custody do get a “Detainee Death Report” when they die in DHS custody. These reports are not an official autopsy. They are not written in a consistent manner with consistent information. Often, the information in these reports conflicts with what is in the preliminary DHS news release and with independent news reporting. Occasionally, there is extensively detailed medical history and details surrounding an individual's death. More commonly, these reports are written in a way that is deliberately vague and most of the time, will not ever state an official cause of death. These reports do not state if an individual has had an official autopsy done or where the information in the reports is pulled from. [TOO POLITICAL? TOO BIASED? DELETE?? : To trust the information in these reports is to trust the information given to us by a state actor who is acting only in the interest of covering their own asses and not giving an accurate statement of the events that have unfolded. To trust this information is to trust a current state that has shown time and time again that they are interested in withholding information at their best, and deliberately spreading misinformation at their worst.] 

3. Individuals who are not in DHS custody when they are killed by DHS do not get a news release from DHS or a “death report”. For these individuals, I have had to rely on news releases and statements from sources that are not the government. Occasionally, there will be an officially available autopsy conducted by a state official or an independent official to verify the official cause of death. Sometimes, the autopsy will not be available but the results will be released to the public through a press release or other news article or statement. For the majority of individuals who are killed by ICE/CBP and are not in custody, there is generally a public documentation of their usually violent and immediate/obvious death ex: being shot by an ICE agent, after fleeing an ICE agent/action into oncoming traffic and being hit by a truck, being left in below freezing temperatures outside at night with no way of communicating or getting to shelter or a safer place. For these deaths, I do rely on more video documentation or news articles that take statements from people who were at the immediate scene. [TOO POLITICAL/BIASED? REMOVE? : Very rarely will the government acknowledge the role their actors have in these deaths, and if they do it is closer to propagandizing the event or detracting from the harm and damage caused of a life lost.]

:::

::: {.text-chunk}

## Why are you including people outside of the USA?

There have been some documented cases where individuals have died in a US territory or outside the US. These cases are much harder for me to track and I have not set up a good system for tracking them, but I have found a few and I believe that it is important to include in this dataset to show that even though this project does not currently have the capacity or resources to be tracking all of these deaths, they are happening and we should be aware that this is a possibility and interaction criteria when dealing with direct interaction with the immigration system of the United States. The individual who died in a US territory, he was in ICE custody when he died and fits the aforementioned inclusion criteria. The other four individuals are women who were found decapitated on the border between the Dominican Republic and Haiti after being deported by ICE from Puerto Rico. These women would not have been murdered if they had not been deported by ICE agents, and therefore fit the aforementioned inclusion criteria as well. I have no doubt that there are dozens, if not hundreds more cases like this but due to many conflating factors, these cases are much harder to track and find reporting on.

:::

::: {.text-chunk}

## Why do you include facilities and transfers?

:::

